services:
  api:
    environment:
      - FLASK_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - .:/app
    command: ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app", "--reload"]
  db:
    environment:
      POSTGRES_DB: loans_dev
